### ISSUE TITLE
[question] how to train on GPU with the Hausdorff Losses?

### ISSUE THREAD

**Issue by neuronflow** [SilmarilBearer/HausdorffLoss#1]
Is it possible to train on GPU with `HausdorffDTLoss` or `HausdorffERLoss`?

How did you train for https://arxiv.org/pdf/1904.10030.pdf ?

**Comment by PatRyg99** [comment]
Loss itself is always on cpu in my implementation since I use numpy. But training a net on gpu is no problem, since you only put output onto cpu once it is being calculated. I guess if you really want to calculate loss on gpu you could check up `cupy` library, though I don't know what it has to offer.

I haven't run any experiments in paper, I've only done an implementation based on provided description of methods. I'm not an author of a paper so it's not an official implementation - afaik there's no official implementation anywhere.

**Comment by umutdundar99** [comment]
i can recomend you some tricks to work on gpu on either tf and torch @neuronflow if you are still interested

**Comment by haibinswe** [comment]
> i can recomend you some tricks to work on gpu on either tf and torch @neuronflow if you are still interested

Hello, I'm very interested in implementing HausdorffDTLoss for training 3d medical image segmentation, could you please provide some tricks for me about it?

**Comment by neuronflow** [comment]
@umutdundar99, a GPU implementation of Hausdorff loss would definitely be interesting! Apparently not only for me :)
